### ISSUE TITLE
Possible Memory Leak

### ISSUE THREAD

**Issue by orcusbeat** [jlplenio/crude-twitch-viewer-bot#48] opened 2022-10-04 09:05 UTC
I believe i have noticed a memory leak. After a little while the RAM increases by quite a bit. Even after destroying all instances the exe still uses 3 sometimes 4 gbs of RAM on its on with no chrome or node instances running. The longer duration the program is run for the more memory it seems to use, instances will begin to die, etc... 

I am on a system with 32gb of RAM and that seems to be the bottle neck, My CPU doesnt peak above 50% Proxies are from the recommended supplier, and i have a gigabit fiber internet connection. i can run almost 40 headless instances before i start having issues.

Are there any recommendations to decrease the RAM usage and increase instances?

Thank you!

**Comment by orcusbeat** [comment] 2022-10-04 20:17
![Screen Shot 2022-10-04 at 1 16 28 PM](https://user-images.githubusercontent.com/102833140/193917753-fe74e5ae-6e65-4465-b268-cae425c24c85.png)

This is with about 25 instances running, There are also a lot of chrome instances open in task manager outside of this process.

**Comment by shukamu95** [comment] 2022-10-07 22:12
i notice same thing here.

My cpu barely goes up 10%, but memory ram slowly increase overtime.

**Comment by jlplenio** [comment] 2022-10-10 16:16
Thank you for the information and screenshots. I will look into it.

**Comment by AmonStrix** [comment] 2022-10-22 21:07
Same problem here memory leak after close it thanks for the software

**Comment by jlplenio** [comment] 2022-10-26 08:30
https://github.com/bloomberg/memray

**Comment by jlplenio** [comment] 2022-11-07 22:48
The memory leak seems to be caused by playwright, https://github.com/microsoft/playwright/issues/6319.

I implemented an automatic restart in #57, so that every instance restarts on its own every 8-12minutes
I am not fully happy with this solution because just by chance many instances could restart simultaneously.
Which could cause 1. a CPU usage spike and 2. a temporary viewer count increases because one instances is counted twice.
In the future, I will implement a restart-routine, which restarts all instances in order with breaks of perhaps 10 min/instances-count. With 100 instances, this would mean that there is an instance restart every 6s. Hmm.

Interested to hear your reports on the current implementation.

**Comment by shukamu95** [comment] 2022-11-08 22:53
@jlplenio the memory leak is gone, thank you!

The solution really cause 1. cpu usage spikes (not a big issue for me) and 2. temporary viewer, i'm consern on temporary count increase viewers as i guess twitch can detect the bot because two viewers from same proxy, not sure if i'm right and not sure if twitch really matters for people using bot haha

Two thing I realized, if CTVB try to reload a instance and it fail for any reason, the instance die and watching/alive decrease as normal and we need to spawn new one. Can you create a way so we set max instances alive, and if some instance die CTVB auto create new one to fix this problem?
And view online/ vod views increase too, not a problem on my perspective. 

Regards,

**Comment by jlplenio** [comment] 2022-11-09 10:34
Thank you for your feedback @shukamu95. I will think about a solution. One thing is clear,
that I won't implement a fully automated solution. I still want a human to control and monitor the tool.
This naturally reduces the opportunity for abuse and commercialization of the tool.

**Comment by jlplenio** [comment] 2022-11-12 16:19
I was running 100 viewers at 160p with 32GB RAM without problems.

**Comment by shukamu95** [comment] 2022-11-12 18:56
10-20% in additional viewers caused by the automated restarts is not a big problem if twitch don't matters, live looks more organic with this in my perspective. But CPU usage spikes is killing to stream, play valorant and run 40 viewers, alot fps drop on valorant... Is possible to test other chrominium based browser like opera or edge and see if it is better than chrome in CPU usage?

Just a question, are you running a 24/7 live @jlplenio if yes for how long? Or just put bots to work when you're live or testing something? I realized we can make some coins with this bot on twitch if you run 24/7 live and configure in right way affiliate ad settings. My only doub't is if twitch matters haha, i guess no as i will receive my first pay check day 15, btw, send your paypal so i can tip a coffe to you man!

**Comment by jlplenio** [comment] 2022-11-13 12:16
Thank you, @shukamu95, for your reports. I agree, the viewer count due to the restarts does look dynamic. CTVB is really not intended to be run on the same system that you stream on. You can either only turn restart on when you are on a break, that does work for established and new instances. Or you have to wait for the new implementation of a restart queue, in which case it would restart an instance every 15 seconds in your case (600s / 40 instances).

I do not stream. Nor do I intend to make money with the tool. As stated in the disclaimer, it is for educational purposes only, as I have used Selenium and Playwright for many other projects. However, the few coins from webshare referrals were a surprise and cover my coffee consumption. Thank you, though.

**Comment by shukamu95** [comment] 2022-11-14 01:25
Thanks about auto-restart explanation, i really don't knew it work for established as new instance too.

**Comment by RasperSquee** [comment] 2022-11-16 23:04
If you implement the restart queue, could you make it a choosable option instead of always 10 minutes? 15 minutes for example? Just so there is less potential instance restart overlap.

**Comment by jlplenio** [comment] 2022-11-17 09:35
With the queue, there won't be any overlap. The instances will be restarted on after another. 
With the 40 instances example, with 600s/40 instances = One restart every 15s:
Restart-Instance1, 15s wait, Restart-Instance2, 15s wait, Restart-Instance3 and so on.

But yes, I can either make a config file or make it available in the GUI

**Comment by jlplenio** [comment] 2023-01-14 18:33
> With the queue, there won't be any overlap. The instances will be restarted on after another. With the 40 instances example, with 600s/40 instances = One restart every 15s: Restart-Instance1, 15s wait, Restart-Instance2, 15s wait, Restart-Instance3 and so on.

Implemented in https://github.com/jlplenio/crude-twitch-viewer-bot/releases/tag/v0.4.0

**Closed** 2023-01-19 14:03 UTC
Labels: enhancement
